-- Readiness checks, unit standards, and the quarterly deep clean.
-- RUN IN THE SUPABASE SQL EDITOR BEFORE DEPLOYING.
--
-- What happened on 4 Sep 2026 at Tropicana A5: the unit sat empty for five
-- days, the cleaner washed a muddy sofa cover, and the next guest walked
-- into a bare sofa, an empty soap dispenser, a rusty oven and dirty walls.
-- Nobody had looked at the unit between the clean and the arrival, and
-- nobody upstream knew the cover was off. With fourteen villas Era cannot
-- be that person, so the cleaner certifies her own work with photos and
-- Maya checks them; Era only hears about the exceptions.
--
-- Three things:
--
--   housekeeping_readiness   one row per turnover / pre-arrival / deep clean:
--                            the photos the housekeeper sent when she said
--                            "done", what the vision check made of them, and
--                            what she said was running low. pass / flagged /
--                            unchecked — the last one is a finding too.
--
--   unit_standards           per villa: the minimum kit (kettle, microwave,
--                            mirror, iron, towel rack, drying rack...), the
--                            consumables par list, and the photo spots the
--                            readiness check asks for. Audited once by Era,
--                            gaps become maintenance items for the owner.
--
--   deep_clean               a fifth task kind — quarterly, on a vacant day
--                            when there is one: walls, oven, exterior
--                            windows, grout, pool furniture, dispenser.

create table if not exists housekeeping_readiness (
  id                bigint generated by default as identity primary key,
  task_id           bigint references housekeeping_tasks(id) on delete set null,
  slug              text not null,
  kind              text not null,                 -- the task kind it certifies
  guest_in_date     date,                          -- who it is for, if anyone
  by_staff_id       bigint references staff(id),
  status            text not null default 'awaiting',   -- awaiting|pass|flagged|unchecked
  photos            jsonb not null default '[]'::jsonb,
  checks            jsonb not null default '[]'::jsonb, -- [{spot, ok, note}]
  flags             text[] not null default '{}',       -- what Era was told
  restock           text,                               -- what she said is low
  asked_at          timestamptz not null default now(),
  closed_at         timestamptz,
  era_notified_at   timestamptz,
  created_at        timestamptz not null default now(),
  unique (task_id)
);

create index if not exists hk_ready_slug_idx  on housekeeping_readiness(slug, asked_at desc);
create index if not exists hk_ready_open_idx  on housekeeping_readiness(status, asked_at) where status = 'awaiting';

create table if not exists unit_standards (
  slug          text primary key,
  -- [{key, label, present: true|false|null, note}] — null = not audited yet
  kit           jsonb not null default '[]'::jsonb,
  -- [{key, label, par}] — what the consumables box holds when full
  consumables   jsonb not null default '[]'::jsonb,
  -- extra photo spots for this villa beyond the portfolio default
  photo_spots   jsonb not null default '[]'::jsonb,
  notes         text,
  audited_at    timestamptz,
  audited_by    text,
  updated_at    timestamptz not null default now()
);

-- The deep clean is anchored the way the inspection is: to the last one
-- done or already asked for, staggered by villa on the first run.
update settings
set value = value || jsonb_build_object(
  'deep_clean_every_days', 90,
  'readiness_kinds', jsonb_build_array('turnover', 'pre_arrival', 'deep_clean'),
  'readiness_timeout_hours', 20,
  'readiness_min_photos', 4
)
where key = 'housekeeping';

-- The portfolio-wide standard. A villa's own row overrides; this is what a
-- new villa starts from. Era edits it from the Schedule page.
insert into settings (key, value)
select 'housekeeping_standard', jsonb_build_object(
  'kit', jsonb_build_array(
    jsonb_build_object('key', 'kettle',       'label', 'Kettle'),
    jsonb_build_object('key', 'microwave',    'label', 'Microwave'),
    jsonb_build_object('key', 'mirror',       'label', 'Full-length mirror'),
    jsonb_build_object('key', 'iron',         'label', 'Iron and ironing board'),
    jsonb_build_object('key', 'towel_rack',   'label', 'Towel rack or ladder'),
    jsonb_build_object('key', 'drying_rack',  'label', 'Drying rack by the pool'),
    jsonb_build_object('key', 'hairdryer',    'label', 'Hairdryer'),
    jsonb_build_object('key', 'sofa_covers',  'label', 'Spare set of sofa covers'),
    jsonb_build_object('key', 'dispenser',    'label', 'Water dispenser, hot and cold, sanitised sticker dated'),
    jsonb_build_object('key', 'pool_cushions','label', 'Pool furniture cushions clean, no mould')
  ),
  'consumables', jsonb_build_array(
    jsonb_build_object('key', 'hand_soap',    'label', 'Hand soap (bathroom and kitchen)', 'par', 2),
    jsonb_build_object('key', 'shower_gel',   'label', 'Shower gel',                        'par', 1),
    jsonb_build_object('key', 'shampoo',      'label', 'Shampoo',                           'par', 1),
    jsonb_build_object('key', 'dish_soap',    'label', 'Dish soap and sponge',              'par', 1),
    jsonb_build_object('key', 'kitchen_roll', 'label', 'Kitchen roll or napkins',           'par', 2),
    jsonb_build_object('key', 'toilet_roll',  'label', 'Toilet roll',                       'par', 4),
    jsonb_build_object('key', 'bin_bags',     'label', 'Bin bags',                          'par', 10),
    jsonb_build_object('key', 'water',        'label', 'Dispenser gallon plus 2 sealed bottles', 'par', 1)
  ),
  'photo_spots', jsonb_build_array(
    jsonb_build_object('key', 'living',   'id', 'ruang tamu (sofa dengan sarungnya)',           'en', 'Living room, sofa with its cover on'),
    jsonb_build_object('key', 'kitchen',  'id', 'dapur (meja, kompor, dan bagian dalam oven)',  'en', 'Kitchen: counter, hob and inside the oven'),
    jsonb_build_object('key', 'bathroom', 'id', 'kamar mandi (sabun dan sabun mandi terisi)',   'en', 'Bathroom with soap and shower gel stocked'),
    jsonb_build_object('key', 'bedroom',  'id', 'kamar tidur (tempat tidur sudah rapi)',        'en', 'Bedroom, bed made'),
    jsonb_build_object('key', 'walls',    'id', 'dinding yang paling kotor sebelumnya',         'en', 'The wall that was dirtiest'),
    jsonb_build_object('key', 'pool',     'id', 'area kolam dan kursinya',                      'en', 'Pool area and its furniture'),
    jsonb_build_object('key', 'box',      'id', 'kotak perlengkapan (sabun, tisu, kantong sampah)', 'en', 'The consumables box')
  )
)
where not exists (select 1 from settings s where s.key = 'housekeeping_standard');
