-- Asks, photos and events: the three records the staff chat was missing.
-- RUN IN THE SUPABASE SQL EDITOR BEFORE OR AFTER DEPLOYING — the code
-- tolerates a database where these tables do not exist yet (it falls back
-- to the old settings blobs and the old quoted-message heuristics), so the
-- deploy is safe either way. Everything below is additive.
--
-- Why (audit of 8 Sep 2026): Maya decided what a housekeeper or Era meant
-- from hidden server state — twelve handlers in a fixed order, each with
-- its own regexes and its own "open window". The person was answering a
-- message; the code was answering a state. Every misfiling of the first
-- week (a day-off note recorded as an inspection finding, routine-clean
-- photos filed as a maintenance ticket, "siap" closing a villa, a pan
-- estimate landing on the wrong ticket) descends from that.
--
--   staff_asks         every question Maya puts to a person, with the
--                      WhatsApp message id it went out as, what it is about
--                      and when it stops being open. A reply that quotes the
--                      message, or taps its button, is routed by this row
--                      and never by guessing.
--   staff_photos       every photo a staff member sends, once, with the
--                      message id it arrived in and where it ended up
--                      (ticket, task, readiness check, inspection round) or
--                      that it is still parked / suggested. Replaces the
--                      photo_by_wamid, maintenance_pending_photos and
--                      maint_photo_suggestions settings blobs, which lost
--                      entries whenever two lambdas wrote at once.
--   maintenance_events / housekeeping_events
--                      append-only history of what happened to a ticket or
--                      a visit, who did it, and via which message. The
--                      status columns stay authoritative for now; the log
--                      is what the console, the owner page and retries read.

create table if not exists staff_asks (
  id             bigint generated by default as identity primary key,
  wa_num         text not null,
  staff_id       bigint references staff(id) on delete set null,
  -- task | inspection | chase | readiness | photo | villa_pick |
  -- schedule_pick | question | onboarding
  kind           text not null,
  target_type    text,                  -- housekeeping_task | maintenance_item | housekeeping_readiness | housekeeping_inspection
  target_id      bigint,
  -- several targets at once (the evening chase lists two villas)
  target_ids     bigint[] not null default '{}',
  wa_message_id  text,                  -- the outbound message this ask went out as
  payload        jsonb not null default '{}'::jsonb,
  asked_at       timestamptz not null default now(),
  expires_at     timestamptz,
  answered_at    timestamptz,
  answer         jsonb,
  created_at     timestamptz not null default now()
);
create unique index if not exists staff_asks_wamid_uniq on staff_asks (wa_message_id) where wa_message_id is not null;
create index if not exists staff_asks_open_idx on staff_asks (wa_num, asked_at desc) where answered_at is null;
create index if not exists staff_asks_target_idx on staff_asks (target_type, target_id);

create table if not exists staff_photos (
  id             bigint generated by default as identity primary key,
  path           text not null unique,  -- storage path in maintenance-photos
  wa_num         text,
  staff_id       bigint references staff(id) on delete set null,
  wa_message_id  text,                  -- the inbound message it arrived in
  caption        text,
  source         text,                  -- maintenance | inspection | readiness | proof | parked
  -- parked | attached | suggested | rejected | proof
  status         text not null default 'parked',
  item_id        bigint references maintenance_items(id) on delete set null,
  task_id        bigint references housekeeping_tasks(id) on delete set null,
  readiness_id   bigint references housekeeping_readiness(id) on delete set null,
  inspection_id  bigint references housekeeping_inspections(id) on delete set null,
  -- for suggestions: which tickets a model thought it might show
  suggested_for  bigint[] not null default '{}',
  why            text,
  received_at    timestamptz not null default now(),
  decided_at     timestamptz,
  decided_by     text
);
create index if not exists staff_photos_wamid_idx on staff_photos (wa_message_id);
create index if not exists staff_photos_num_idx on staff_photos (wa_num, received_at desc);
create index if not exists staff_photos_item_idx on staff_photos (item_id);
create index if not exists staff_photos_open_idx on staff_photos (wa_num, status) where status in ('parked', 'suggested');

create table if not exists maintenance_events (
  id             bigint generated by default as identity primary key,
  item_id        bigint not null references maintenance_items(id) on delete cascade,
  kind           text not null,         -- created | published | heads_up | approved | declined | completed | reopened | moved | snoozed | estimated | assigned | photo | note | notified_owner | notified_era
  actor          text,                  -- Era | Ita | owner (link) | Maya | admin
  payload        jsonb not null default '{}'::jsonb,
  wa_message_id  text,                  -- the message that caused it (inbound) or carried it (outbound)
  at             timestamptz not null default now()
);
create index if not exists maintenance_events_item_idx on maintenance_events (item_id, at);

create table if not exists housekeeping_events (
  id             bigint generated by default as identity primary key,
  task_id        bigint not null references housekeeping_tasks(id) on delete cascade,
  kind           text not null,         -- generated | notified | chased | confirmed | done | moved | skipped | cannot | reassigned | photo | readiness_opened | readiness_closed | uncovered
  actor          text,
  payload        jsonb not null default '{}'::jsonb,
  wa_message_id  text,
  at             timestamptz not null default now()
);
create index if not exists housekeeping_events_task_idx on housekeeping_events (task_id, at);

-- A housekeeper's channel: what Maya has learnt about reaching this person.
-- Derived hourly from wa_messages and staff_asks; kept as a row so the
-- sweeps, the chase and Era's brief read one fact instead of re-deriving
-- it three ways. mode: ok | quiet (reads, does not reply) | dead (nothing
-- delivered for two days).
create table if not exists staff_channel (
  staff_id          bigint primary key references staff(id) on delete cascade,
  wa_num            text,
  mode              text not null default 'ok',
  last_inbound_at   timestamptz,
  last_read_at      timestamptz,
  undelivered_since timestamptz,
  ignored_asks_7d   integer not null default 0,
  asks_7d           integer not null default 0,
  era_told_at       timestamptz,
  note              text,
  updated_at        timestamptz not null default now()
);
