-- Housekeeping schedule.
-- RUN IN THE SUPABASE SQL EDITOR BEFORE DEPLOYING.
--
-- Cleaning has been coordinated by hand: nobody's system knows when a tenant
-- leaves, when the next one arrives after a gap, or when a unit was last
-- looked at. Nothing catches mould or a slow leak between tenancies until it
-- is expensive.
--
-- These are LONG-TERM rentals, so the short-let turnover playbook mostly does
-- not apply: cleans DURING a tenancy dominate, and the empty weeks between
-- tenants are the risk. Five kinds of visit:
--
--   turnover      a tenant left today
--   during_stay   a long stay gets a clean every so often
--   pre_arrival   someone arrives after the villa stood empty
--   vacant_upkeep an empty villa still needs to show well for viewings
--   inspection    every two weeks, look for mould, damp and damage, with
--                 photos — this one feeds the owner's weekly report and is
--                 the reason the whole schedule pays for itself
--
-- The unique constraint is what makes the generator safe to run every hour:
-- re-deriving the same task is a no-op rather than a duplicate message.

create table if not exists housekeeping_tasks (
  id                bigint generated by default as identity primary key,
  slug              text not null,              -- catalog unit
  task_date         date not null,
  kind              text not null,              -- turnover|during_stay|pre_arrival|vacant_upkeep|inspection
  -- planned → notified → confirmed → done, or skipped
  status            text not null default 'planned',
  assigned_staff_id bigint references staff(id),
  same_day          boolean not null default false,   -- someone arrives the day they leave
  guest_out_date    date,
  guest_in_date     date,
  notified_at       timestamptz,
  confirmed_at      timestamptz,
  done_at           timestamptz,
  next_followup_at  timestamptz,
  photos            jsonb not null default '[]'::jsonb,
  notes             text,
  thread            jsonb not null default '[]'::jsonb,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (slug, task_date, kind)
);

create index if not exists hk_date_idx   on housekeeping_tasks(task_date, status);
create index if not exists hk_staff_idx  on housekeeping_tasks(assigned_staff_id, task_date);
create index if not exists hk_notify_idx on housekeeping_tasks(notified_at) where notified_at is null;

-- Inspection reports: a housekeeper's photo round, kept as its own record so
-- it can be attached to the owner's weekly report even when it found nothing
-- wrong. "We looked and everything is fine" is the point, not a null result.
create table if not exists housekeeping_inspections (
  id            bigint generated by default as identity primary key,
  slug          text not null,
  task_id       bigint references housekeeping_tasks(id) on delete set null,
  inspected_on  date not null default (now() at time zone 'Asia/Makassar')::date,
  by_staff_id   bigint references staff(id),
  photos        jsonb not null default '[]'::jsonb,
  findings      text,
  -- Anything that became a work order, so the owner's report can link them.
  item_ids      bigint[] not null default '{}',
  reported_at   timestamptz not null default now(),
  unique (slug, inspected_on)
);

create index if not exists hk_insp_slug_idx on housekeeping_inspections(slug, inspected_on desc);

-- Thresholds live here, not in the code, so Era can change how often a long
-- stay is cleaned without a deploy.
insert into settings (key, value)
select 'housekeeping', jsonb_build_object(
  'during_stay_min_nights', 14,   -- a stay this long gets recurring cleans
  'during_stay_every_days', 7,
  'pre_arrival_vacant_days', 5,   -- empty this long → freshen up before arrival
  'vacant_upkeep_days', 14,       -- empty this long → a visit anyway
  'inspection_every_days', 14,
  'horizon_days', 21,             -- how far ahead tasks are generated
  'notify_daily_cap', 0           -- 0 = paused; arm it in the Command Center
)
where not exists (select 1 from settings s where s.key = 'housekeeping');

-- Campaign row so the schedule appears in the Campaign Command Center with a
-- cap and a pause switch. MUST stay in sync with CAMPAIGN_REGISTRY.
insert into campaigns (name, kind, key, pipeline, mode, status, goal, categories, context, schedule)
select 'Housekeeping', 'always_on', 'housekeeping', 'samba', 'broadcast', 'paused', 'reply',
       array['housekeeping'],
       'Daily cleaning tasks to housekeepers, the week ahead on Mondays, and bi-weekly inspection rounds',
       '{"cron":"generator hourly (relay sweep), notifications daily 09:00 WITA","cap_setting":"housekeeping.notify_daily_cap"}'::jsonb
where not exists (select 1 from campaigns c where c.key = 'housekeeping');
