-- Maintenance items for Samba Realty-managed villas.
-- RUN IN THE SUPABASE SQL EDITOR BEFORE DEPLOYING.
--
-- Flow: Era or a cleaner sends Maya a photo + description on WhatsApp →
-- Maya files an item (status 'new') → Era reviews it in /payouts, adds a
-- cost estimate and decides whether the owner must approve → publish →
-- Maya notifies the owner → owner approves (or it's notify-only) → Era
-- does the work → marks it done → Maya tells the owner. While an approved
-- item sits undone, Maya nudges Era on next_followup_at; if Era replies
-- "next Tuesday", that date becomes the next nudge.

create table if not exists maintenance_items (
  id                bigint generated by default as identity primary key,
  group_key         text not null references statement_groups(key) on delete cascade,
  slug              text,                 -- specific unit, null = whole property
  unit_label        text,                 -- human label as reported ("Unit 1")
  title             text not null,
  description       text,
  photos            jsonb not null default '[]'::jsonb,   -- storage paths
  -- new → pending_approval | scheduled → approved | declined → done
  -- 'scheduled' = notify-only (routine, no approval needed)
  status            text not null default 'new',
  requires_approval boolean not null default true,
  estimated_cost    numeric,
  actual_cost       numeric,
  currency          text not null default 'IDR',
  urgency           text default 'normal',                -- low | normal | urgent
  reported_by_wa    text,
  reported_by_name  text,
  reported_at       timestamptz not null default now(),
  published_at      timestamptz,
  published_by      text,
  notified_at       timestamptz,          -- owner told (null = queued for Maya)
  approved_at       timestamptz,
  approved_by       text,
  declined_at       timestamptz,
  decline_note      text,
  staff_notified_at timestamptz,          -- Era told the owner approved
  completed_at      timestamptz,
  completed_by      text,
  completion_note   text,
  done_notified_at  timestamptz,          -- owner told it's finished
  -- Follow-up loop with Era
  next_followup_at  timestamptz,
  followup_count    integer not null default 0,
  promised_date     date,                 -- "it'll be ready next Tuesday"
  thread            jsonb not null default '[]'::jsonb,   -- {at, who, text} log
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index if not exists maintenance_group_idx  on maintenance_items(group_key, status);
create index if not exists maintenance_status_idx on maintenance_items(status);
create index if not exists maintenance_followup_idx on maintenance_items(next_followup_at)
  where next_followup_at is not null;

-- Private bucket for the photos Era and the cleaners send in.
insert into storage.buckets (id, name, public)
values ('maintenance-photos', 'maintenance-photos', false)
on conflict (id) do nothing;

-- Staff who may file maintenance items by messaging Maya (Era, cleaners).
-- Matching is on the digits of the WhatsApp number.
create table if not exists maintenance_reporters (
  wa_num     text primary key,
  name       text,
  role       text default 'staff',        -- staff | manager
  active     boolean not null default true,
  created_at timestamptz not null default now()
);

-- Campaign row so the sweep appears in the Campaign Command Center with a
-- daily cap and a pause switch. MUST stay in sync with CAMPAIGN_REGISTRY in
-- lib/campaigns.js. Paused until Ikiel arms it in the Command Center.
insert into campaigns (name, kind, key, pipeline, mode, status, goal, categories, context, schedule)
select 'Maintenance', 'always_on', 'maintenance', 'samba', 'broadcast', 'paused', 'click',
       array['maintenance'],
       'Owner approval requests, completion notices, and follow-up nudges to Era',
       '{"cron":"daily 09:00 WITA (wave 0), event-driven on publish/approve/complete","cap_setting":"maintenance.notify_daily_cap","env_gate":"OWNERS_ENABLED=1"}'::jsonb
where not exists (select 1 from campaigns c where c.key = 'maintenance');
