-- The turn ledger: what Maya did with each thing a staff member said.
-- RUN IN THE SUPABASE SQL EDITOR. The code tolerates the table's absence
-- (it stops writing for ten minutes and tries again), so deploy order does
-- not matter. Additive only.
--
-- Why (9 Sep 2026): the weekly review graded Maya's sales replies and could
-- not see the staff side at all. Ikiel's question was a funnel — of what
-- the housekeepers say to Maya, how much did she understand, how much of
-- that became a record, and how much of that record was right. Each row
-- here is one inbound staff message with the answers to those three
-- questions, filled in at the time (layer, outcome, target) and later
-- (corrected_at, when a human changed what she wrote).
--
--   kind       text | photo | tap
--   layer      which part of the dispatcher decided:
--                tap        our own button/list ids (hk:, sched:, villa:, pa:)
--                button     a template quick reply (Sudah selesai / Besok saja / Tidak bisa)
--                reference  a reply to one of Maya's asks (quoted or fresh)
--                rule       a word rule (ack, done, greeting, self-intro, schedule words)
--                photo      the photo router
--                classifier the Haiku intent classifier
--                vocab      the keyword fallback (bocor / rusak / pecah)
--                handler    an earlier handler in the webhook (tukang, onboarding)
--                none       nothing claimed it
--   outcome    recorded | asked | coached | answered | ack | parked | forwarded | error
--   target     the record touched (housekeeping_task, housekeeping_inspection,
--              housekeeping_readiness, maintenance_item)

create table if not exists staff_turns (
  id             bigint generated by default as identity primary key,
  wa_message_id  text unique,
  wa_num         text not null,
  staff_id       bigint references staff(id) on delete set null,
  received_at    timestamptz not null default now(),
  kind           text not null default 'text',
  text           text,
  ref_kind       text,
  layer          text,
  intent         text,
  confidence     text,
  category       text,
  outcome        text,
  target_type    text,
  target_id      bigint,
  detail         jsonb not null default '{}'::jsonb,
  corrected_at   timestamptz,
  correction     jsonb,
  created_at     timestamptz not null default now()
);
create index if not exists staff_turns_num_idx on staff_turns (wa_num, received_at desc);
create index if not exists staff_turns_target_idx on staff_turns (target_type, target_id);
create index if not exists staff_turns_received_idx on staff_turns (received_at desc);
