-- Staff registry: the people who look after the villas.
-- RUN IN THE SUPABASE SQL EDITOR BEFORE DEPLOYING.
--
-- Until now the only record of a team member was maintenance_reporters: a
-- flat allowlist of WhatsApp numbers with no idea which villas anyone
-- covers. That was enough to decide "may this number file a ticket?" and
-- nothing else. Tukang dispatch needs to know who fixes aircon, housekeeping
-- needs to know whose villa is being cleaned, and payroll needs to know who
-- is on a monthly salary. All three want the same table, so it is built once
-- here and maintenance_reporters becomes a fallback.
--
-- Two shapes the real roster forced:
--   roles is an ARRAY. Dian is the pool man on a monthly salary and also the
--   person called for plumbing, small electrical and paint touch-ups, so he
--   belongs in the pool rota and the tukang dropdown at the same time.
--
--   pay_type separates employees from vendors. Salaried people appear on
--   Era's monthly salary sheet and flow through payroll. Per-job vendors
--   (BTC Electric) never do: their invoices are maintenance costs that reach
--   owners as statement expenses. Treating a vendor as staff would bill the
--   same repair twice.

create table if not exists staff (
  id           bigint generated by default as identity primary key,
  name         text not null,
  wa_num       text not null unique,          -- digits only, matched by the webhook
  roles        text[] not null default '{}',  -- manager|housekeeper|pool|gardener|tukang
  trades       text[] not null default '{}',  -- aircon|electrical|plumbing|carpentry|pool|paint|general
  slugs        text[] not null default '{}',  -- catalog slugs covered; empty = island-wide
  pay_type     text default 'salaried',       -- salaried | per_job
  monthly_rate numeric,                       -- salaried only, for the payroll cross-check
  can_report   boolean not null default true, -- may file maintenance items by messaging Maya
  active       boolean not null default true,
  notes        text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists staff_active_idx on staff(active) where active;
create index if not exists staff_roles_idx  on staff using gin(roles);
create index if not exists staff_slugs_idx  on staff using gin(slugs);

-- Seed: the roster as Ikiel gave it on 29 Aug 2026.
--
-- Note this DISAGREES with Era's salary sheet, which still has Putu on the
-- Tropicanas and Ana on Astanine. This table is the truth; the payroll parser
-- will raise the difference as a reconciliation warning rather than quietly
-- follow the older sheet.
--
-- Astanine is Ikiel's own villa. It carries staff costs but is not a catalog
-- unit and never reaches an owner statement, so it appears here as a plain
-- slug with no listing behind it.
insert into staff (name, wa_num, roles, trades, slugs, pay_type, notes) values
  ('Gede Baglug', '6285847163053', '{housekeeper}', '{}',
   '{tropicana-b2,tropicana-b3,tropicana-b5,tropicana-b6}', 'salaried', null),
  ('Naomi', '6282341079324', '{housekeeper}', '{}',
   '{villa-saturno}', 'salaried', null),
  ('Ita', '6285704892074', '{housekeeper}', '{}',
   '{tropicana-a4,tropicana-a5,tropicana-b4}', 'salaried', null),
  ('Ana', '6281237692282', '{housekeeper}', '{}',
   '{lanehaus-1,lanehaus-3}', 'salaried', null),
  ('Putu', '6287862135047', '{housekeeper}', '{}',
   '{haus-1,haus-2,haus-4,haus-5}', 'salaried', null),
  ('Dian', '6281236744565', '{pool,tukang}', '{pool,plumbing,electrical,paint}',
   '{}', 'salaried', 'Pool across the portfolio; also plumbing, small electrical and paint touch-ups.'),
  ('Wayan', '6282236164194', '{pool}', '{pool}',
   '{villa-saturno,astanine}', 'salaried', null),
  ('BTC Electric', '6282339711019', '{tukang}', '{aircon,electrical}',
   '{}', 'per_job', 'Buana Teknik Chiamando. Vendor, invoiced per job, never on payroll.')
on conflict (wa_num) do nothing;

-- Anyone already allowed to file tickets keeps that right: carry the old
-- allowlist across so nobody loses access the moment isReporter starts
-- reading this table first.
--
-- Numbers are normalised on the way in, matching normalizeWa in lib/staff.js
-- and the portal's normalizeWaNumber: a number stored as "0813…" would match
-- nothing, because the webhook always reports the full international form.
with cleaned as (
  select regexp_replace(wa_num, '[^0-9]', '', 'g') as d, name, role, active
  from maintenance_reporters
)
insert into staff (name, wa_num, roles, pay_type, can_report, active)
select coalesce(c.name, 'Unknown'),
       case
         when c.d like '620%'              then '62' || substr(c.d, 4)
         when c.d like '0%'                then '62' || substr(c.d, 2)
         when c.d ~ '^8[12379][0-9]{8,10}$' then '62' || c.d
         else c.d
       end,
       case when c.role = 'manager' then '{manager}'::text[] else '{}'::text[] end,
       'salaried', true, c.active
from cleaned c
where c.d <> ''
on conflict (wa_num) do nothing;
